name: BOSS_reaction_f6d02e635714ffc60129f56c06d3deba
'on':
  repository_dispatch:
    types:
      - f6d02e635714ffc60129f56c06d3deba
jobs:
  boss-at-work:
    runs-on: ubuntu-latest
    steps:
      - name: Post actions status to slack
        run: >
          curl -H 'Accept: application/vnd.github.squirrel-girl-preview+json' -H
          "Authorization: token ${{ secrets.BOSS_TOKEN }}" -d '{"content":"${{
          github.event.client_payload.boss_payload_1 }}"}' -X POST
          https://api.github.com/repos/yaananth/boss-action/issues/comments/${{
          github.event.client_payload.commentId }}/reactions
