
name: BOSS_hello_ac809906-7144-436c-b3c5-e6b7b4230cfc
on: 
  repository_dispatch
    types: [ac809906-7144-436c-b3c5-e6b7b4230cfc]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Hello
    run: |
      echo hey boss!

  