name: BOSS_hello_5d41402abc4b2a76b9719d911017c592
'on':
  repository_dispatch:
    types:
      - 5d41402abc4b2a76b9719d911017c592
jobs:
  boss-at-work:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello
        run: >
          echo hey boss, I got ${{ github.event.client_payload.boss_payload_0
          }}!
      - name: Update issue comment
        uses: simpleactions/create-issue-comment@v1.0.0
        with:
          body: 'hey boss, I got ${{ github.event.client_payload.boss_payload_0 }}!'
          issue_number: 1
          github_token: '${{ secrets.GITHUB_TOKEN }}'
