name: BOSS_hello yash_18777587-e637-4206-8823-24521f97e49f
'on':
  repository_dispatch:
    types:
      - 18777587-e637-4206-8823-24521f97e49f
jobs:
  boss-at-work:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello
        run: |
          echo hey boss!
